version: '3.8'

services:
  neo4j-backup:
    platform: linux/amd64
    image: neo4j:5.12.0
    container_name: neo4j-backup
    volumes:
      - ./docker/neo4j/backup-neo4j.sh:/backup-neo4j.sh
      - ./backups:/backups
    networks:
      - ldf-network
    environment:
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j123
      - NEO4J_BACKUP_DIR=${NEO4J_BACKUP_DIR:-/backups}
    depends_on:
      - neo4j
    command: >
      sh -c "
        chmod +x /backup-neo4j.sh &&
        /backup-neo4j.sh /backups"
    profiles:
      - backup

networks:
  ldf-network:
    external: true
