# Docker Compose Override for Testing/CI Environment
# This file uses tmpfs volumes to ensure fresh databases on every run
# Usage: docker compose -f docker-compose.yml -f docker-compose.override.yml up

version: '3.8'

services:
  mongodb:
    volumes:
      - type: tmpfs
        target: /data/db
        tmpfs:
          size: 1000000000  # 1GB

  neo4j:
    volumes:
      - type: tmpfs
        target: /data
        tmpfs:
          size: 1000000000  # 1GB
      - type: tmpfs
        target: /logs
        tmpfs:
          size: 100000000   # 100MB

  postgres:
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 1000000000  # 1GB

# Remove named volumes since we're using tmpfs
volumes:
  mongodb_data:
    external: false
  neo4j_data:
    external: false
  neo4j_logs:
    external: false
  postgres_data:
    external: false 