openapi: 3.0.0
info:
  title: Update API
  version: 1.0.0
servers:
  - url: http://localhost:8080/entities
    description: Production server
paths:
  /entities:
    post:
      summary: Create a new entity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
      responses:
        '201':
          description: Entity created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
  /entities/{id}:
    put:
      summary: Update an existing entity
      description: |
        This endpoint allows you to update an existing entity body by:
        - Updating its core attributes (name, created, terminated)
        - Adding its metadata
        - Adding its attributes
        - Adding or Updating its relationships
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        description: |
          This request body corresponds to the entity to be updated.
          - It is required to provide the `id` of the entity to be updated.
          
          Updating core attributes:
          - Only `name`, `created` and `terminated` can be updated.

          Adding a new Relationship:
          - It is required to provide the `id`,`relatedEntityId`, `name`, and `startTime` of the relationship to be added.
          - To add a relationship, its `id` must not be an existing id.

          Updating an existing Relationship:
          - It is required to provide the `id` of the relationship to be updated.
          - To update a relationship, its `id` must be an existing id.
          - Only the `startTime` and `endTime` of the relationship can be updated.

        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
      responses:
        '200':
          description: Entity updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
    delete:
      summary: Delete an entity
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Entity deleted
components:
  schemas:
    Entity:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        kind:
          $ref: '#/components/schemas/Kind'
          readOnly: true
        created:
          type: string
          format: date-time
        terminated:
          type: string
          format: date-time
          nullable: true
        name:
          $ref: '#/components/schemas/TimeBasedValue'
        metadata:
          type: object
          additionalProperties: true
        attributes:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/TimeBasedValue'
        relationships:
          type: array
          items:
            type: object
            properties:
              key:
                type: string
              value:
                $ref: '#/components/schemas/Relationship'
    Kind:
      type: object
      properties:
        major:
          type: string
        minor:
          type: string
    TimeBasedValue:
      type: object
      properties:
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
          nullable: true
        value:
          type: object
          additionalProperties: true
    Relationship:
      type: object
      properties:
        relatedEntityId:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
          nullable: true
        id:
          type: string
        name:
          type: string