version: '3.8'

services:
  neo4j-test:
    image: neo4j:4.4
    platform: linux/arm64
    container_name: neo4j-test
    ports:
      - "7475:7474"  # HTTP (Neo4j Browser)
      - "7688:7687"  # Bolt protocol (driver/client connection)
    volumes:
      - ./test-data/neo4j:/data
      - ./test-logs/neo4j:/logs
      - ./test-plugins/neo4j:/plugins
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_offheap_max__size=512M
      - NEO4J_AUTH=neo4j/neo4j123
    networks:
      - test-network

  mongodb-test:
    image: mongo:6
    platform: linux/arm64
    container_name: mongodb-test
    ports:
      - "27018:27017"
    volumes:
      - ./test-data/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=test123456
    networks:
      - test-network

  crud-service-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    platform: linux/arm64
    container_name: crud-service-test
    environment:
      - NEO4J_URI=bolt://neo4j-test:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j123
      - MONGO_URI=mongodb://admin:test123456@mongodb-test:27017
      - MONGO_DB_NAME=testdb
      - MONGO_COLLECTION=metadata
    depends_on:
      neo4j-test:
        condition: service_healthy
      mongodb-test:
        condition: service_healthy
    networks:
      - test-network

networks:
  test-network:
    name: test-network
    driver: bridge 