version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    platform: linux/arm64
    container_name: neo4j-local
    ports:
      - "7474:7474"  # HTTP (Neo4j Browser)
      - "7687:7687"  # Bolt protocol (driver/client connection)
    volumes:
      - ./data/neo4j:/data
      - ./logs/neo4j:/logs
      - ./plugins/neo4j:/plugins
      - ./import/neo4j:/var/lib/neo4j/import
    environment:
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_offheap_max__size=1G
      - NEO4J_dbms_security_auth_enabled=true
      - NEO4J_AUTH=neo4j/neo4j123
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crud-network

  mongo:
    image: mongo:6
    platform: linux/arm64
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand(\"ping\").ok", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crud-network

  crud-service:
    build:
      context: .
      dockerfile: Dockerfile.crud
    platform: linux/arm64
    ports:
      - "50051:50051"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j123
      - NEO4J_TESTING_DB_URI=bolt://neo4j:7687
      - NEO4J_TESTING_USERNAME=neo4j
      - NEO4J_TESTING_PASSWORD=neo4j123
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=testdb
      - MONGO_COLLECTION=metadata
      - MONGO_ADMIN_USER=admin
      - MONGO_ADMIN_PASSWORD=test123456
      - MONGO_TEST_USER=testuser
      - MONGO_TEST_PASSWORD=test123456
      - CRUD_SERVICE_HOST=0.0.0.0
      - CRUD_SERVICE_PORT=50051
    depends_on:
      neo4j:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - crud-network

networks:
  crud-network:
    driver: bridge
