version: '3'

services:
  neo4j:
    image: neo4j:4.4
    platform: linux/arm64
    container_name: neo4j-local
    ports:
      - "7474:7474"  # HTTP (Neo4j Browser)
      - "7687:7687"  # Bolt protocol (driver/client connection)
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./plugins:/plugins
      - ./import:/var/lib/neo4j/import
    environment:
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_offheap_max__size=1G
    env_file:
      - ./config.env
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
