name: CRUD API Test

on:
  push:
    branches: [ main ]
    paths:
      - 'design/crud-api/**'
      - 'Dockerfile.crud'
      - 'docker-compose.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'design/crud-api/**'
      - 'Dockerfile.crud'
      - 'docker-compose.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and test CRUD service
      run: |
        # Build CRUD service
        docker compose build crud
        
        # Start required dependencies
        docker compose up -d mongodb neo4j
        
        # Wait for dependencies to be healthy
        echo "Waiting for MongoDB and Neo4j to be healthy..."
        docker compose ps
        
        # Start CRUD service in detached mode
        echo "Starting CRUD service and running tests..."
        docker compose up -d crud
        
        # Wait for a few seconds to allow tests to complete
        sleep 10
        
        # Check the logs for test results
        if docker compose logs crud | grep -q "FAIL"; then
          echo "CRUD API tests failed!"
          echo "Container logs:"
          docker compose logs crud
          docker compose down
          exit 1
        elif docker compose logs crud | grep -q "Starting CRUD service"; then
          echo "CRUD API tests passed!"
          echo "Container logs:"
          docker compose logs crud
        else
          echo "Could not determine test status from logs"
          echo "Container logs:"
          docker compose logs crud
          docker compose down
          exit 1
        fi
        
        # Cleanup
        docker compose down 