name: Update API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    services:
      neo4j:
        image: neo4j:5
        ports:
          - 7687:7687
        env:
          NEO4J_AUTH: neo4j/test123456
        options: >-
          --health-cmd "wget -q --spider http://localhost:7474 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok' --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Install required dependencies
      run: |
        apt-get update
        apt-get install -y wget gnupg python3 python3-pip golang-go netcat-openbsd curl
        # Install grpcurl
        wget https://github.com/fullstorydev/grpcurl/releases/download/v1.8.7/grpcurl_1.8.7_linux_x86_64.tar.gz
        tar -xzf grpcurl_1.8.7_linux_x86_64.tar.gz
        mv grpcurl /usr/local/bin/
        rm grpcurl_1.8.7_linux_x86_64.tar.gz

    - name: Install Ballerina
      run: |
        wget https://dist.ballerina.io/downloads/2201.12.2/ballerina-2201.12.2-swan-lake-linux-x64.deb
        dpkg -i ballerina-2201.12.2-swan-lake-linux-x64.deb || true
        apt-get install -f -y

    - name: Set up Database Environment Variables
      run: |
        echo "NEO4J_URI=bolt://neo4j:7687" >> $GITHUB_ENV
        echo "NEO4J_USER=neo4j" >> $GITHUB_ENV
        echo "NEO4J_PASSWORD=test123456" >> $GITHUB_ENV
        echo "MONGO_URI=mongodb://mongo:27017" >> $GITHUB_ENV
        echo "MONGO_DB_NAME=testdb" >> $GITHUB_ENV
        echo "MONGO_COLLECTION=entities" >> $GITHUB_ENV
        echo "CRUD_SERVICE_HOST=0.0.0.0" >> $GITHUB_ENV
        echo "UPDATE_SERVICE_HOST=0.0.0.0" >> $GITHUB_ENV
        echo "CRUD_SERVICE_PORT=50051" >> $GITHUB_ENV
        echo "UPDATE_SERVICE_PORT=8080" >> $GITHUB_ENV
        # Add test-specific environment variables
        echo "TEST_CRUD_SERVICE_HOST=localhost" >> $GITHUB_ENV
        echo "TEST_UPDATE_SERVICE_HOST=localhost" >> $GITHUB_ENV

    - name: Run CRUD Server
      shell: bash -l {0}
      run: |
        cd design/crud-api
        go build ./...
        go build -o crud-service cmd/server/service.go cmd/server/utils.go
        go test -v ./...
        # Start the service with environment variables
        CRUD_SERVICE_HOST=0.0.0.0 CRUD_SERVICE_PORT=50051 ./crud-service &
        echo $! > crud-service.pid
        # Wait for the service to be ready
        for i in {1..30}; do
          if nc -z 0.0.0.0 50051; then
            echo "CRUD service is up and running"
            # Additional wait to ensure service is fully initialized
            sleep 5
            # Verify service is responding using gRPC health check
            echo "Testing CRUD service connection..."
            grpcurl -plaintext 0.0.0.0:50051 grpc.health.v1.Health/Check || echo "gRPC health check failed, but port is open"
            echo "CRUD service health check completed"
            break
          fi
          echo "Waiting for CRUD service to start... ($i/30)"
          sleep 1
        done
        if ! nc -z 0.0.0.0 50051; then
          echo "CRUD service failed to start"
          echo "Checking service logs:"
          cat crud-service.log || true
          exit 1
        fi
        echo "CRUD service is ready for tests"
    
    - name: Test Update API
      shell: bash -l {0}
      run: |
        cd design/update-api
        # Run tests and capture the exit code
        echo "CRUD_SERVICE_HOST=$CRUD_SERVICE_HOST"
        echo "CRUD_SERVICE_PORT=$CRUD_SERVICE_PORT"
        echo "UPDATE_SERVICE_HOST=$UPDATE_SERVICE_HOST"
        echo "UPDATE_SERVICE_PORT=$UPDATE_SERVICE_PORT"
        echo "TEST_CRUD_SERVICE_HOST=$TEST_CRUD_SERVICE_HOST"
        echo "TEST_UPDATE_SERVICE_HOST=$TEST_UPDATE_SERVICE_HOST"
        # Check if CRUD service is still running and accessible
        echo "Verifying CRUD service is still accessible..."
        if nc -z $TEST_CRUD_SERVICE_HOST $CRUD_SERVICE_PORT; then
          echo "CRUD service is running on $TEST_CRUD_SERVICE_HOST:$CRUD_SERVICE_PORT"
          # Try to ping the health endpoint using gRPC
          grpcurl -plaintext $TEST_CRUD_SERVICE_HOST:$CRUD_SERVICE_PORT grpc.health.v1.Health/Check || echo "gRPC health check failed, but port is open"
        else
          echo "ERROR: CRUD service is not accessible on $TEST_CRUD_SERVICE_HOST:$CRUD_SERVICE_PORT"
          echo "This may cause the tests to fail. Checking process status..."
          ps aux | grep crud-service
        fi
        # Run tests with test-specific host
        echo "Checking gRPC with grpcurl..."
        grpcurl -v -plaintext localhost:50051 list || echo "grpcurl failed to connect"
        CRUD_SERVICE_HOST=$TEST_CRUD_SERVICE_HOST UPDATE_SERVICE_HOST=$TEST_UPDATE_SERVICE_HOST bal test || TEST_EXIT_CODE=$?
        # Store the exit code for later use
        echo "TEST_EXIT_CODE=$TEST_EXIT_CODE" >> $GITHUB_ENV
        cd ../crud-api
        kill $(cat crud-service.pid)
        # Exit with the test exit code to ensure workflow fails if tests failed
        exit ${TEST_EXIT_CODE:-0}

    - name: Check Test Results
      if: failure()
      run: |
        echo "Tests failed with exit code: $TEST_EXIT_CODE"
        echo "Please check the test output above for details."