name: Test with Neo4j

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - uses: actions/checkout@v3

    - name: Install required dependencies
      run: |
        apt-get update
        apt-get install -y wget gnupg systemd

    - name: Install Neo4j
      run: |
        wget -O - https://debian.neo4j.com/neotechnology.gpg.key | apt-key add -
        echo 'deb https://debian.neo4j.com stable latest' | tee /etc/apt/sources.list.d/neo4j.list
        apt-get update
        apt-get install -y neo4j

    - name: Start Neo4j
      run: |
        neo4j start
        sleep 10  # Wait for Neo4j to start

    - name: Set up Mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge,defaults
        channel-priority: strict
        activate-environment: ldf-tests
        environment-file: environment.yml
        auto-activate-base: false
        miniconda-version: "latest"

    - name: Install mamba
      shell: bash -l {0}
      run: |
        conda install -n base -c conda-forge mamba

    - name: Activate Mamba environment
      shell: bash -l {0}
      run: mamba activate ldf-tests

    - name: Set Neo4j environment variables
      run: |
        echo "NEO4J_TESTING_DB_URI=bolt://localhost:7687" >> $GITHUB_ENV
        echo "NEO4J_TESTING_USERNAME=neo4j" >> $GITHUB_ENV
        echo "NEO4J_TESTING_PASSWORD=neo4j" >> $GITHUB_ENV

    - name: Ensure systemd users and groups
      run: |
        getent passwd systemd-network || useradd -r systemd-network
        getent group systemd-journal || groupadd -r systemd-journal

    - name: Run tests
      shell: bash -l {0}
      run: |
        python -m pytest design/tests/neo4j/test_local_instance.py -v 