name: Update API Test (Old)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install required dependencies
      run: |
        apt-get update
        apt-get install -y wget gnupg python3 python3-pip golang-go netcat-openbsd

    - name: Install Neo4j
      run: |
        wget -O - https://debian.neo4j.com/neotechnology.gpg.key | apt-key add -
        echo 'deb https://debian.neo4j.com stable latest' | tee /etc/apt/sources.list.d/neo4j.list
        apt-get update
        apt-get install -y neo4j

    - name: Configure Neo4j
      run: |
        # Set Neo4j password
        echo "dbms.security.auth_enabled=true" >> /etc/neo4j/neo4j.conf
        echo "dbms.security.procedures.unrestricted=apoc.*" >> /etc/neo4j/neo4j.conf
        echo "dbms.security.procedures.allowlist=apoc.*" >> /etc/neo4j/neo4j.conf
        # Set initial password
        neo4j-admin dbms set-initial-password test123456

    - name: Install MongoDB
      run: |
        # Install libssl1.1
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb || true
        apt-get install -f -y

        # Add MongoDB repository
        wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        apt-get update
        apt-get install -y mongodb-org

    - name: Install Ballerina
      run: |
        wget https://dist.ballerina.io/downloads/2201.12.2/ballerina-2201.12.2-swan-lake-linux-x64.deb
        dpkg -i ballerina-2201.12.2-swan-lake-linux-x64.deb || true
        apt-get install -f -y

    - name: Start Services
      run: |
        # Create MongoDB directories and set permissions
        mkdir -p /data/db
        chown -R mongodb:mongodb /data/db
        mkdir -p /var/log/mongodb
        chown -R mongodb:mongodb /var/log/mongodb

        # Start Neo4j
        /usr/bin/neo4j start
        # Start MongoDB
        /usr/bin/mongod --dbpath /data/db --logpath /var/log/mongodb/mongod.log --fork
        # Wait for services to be ready
        sleep 10

    - name: Set up Database Environment Variables
      run: |
        echo "NEO4J_URI=bolt://localhost:7687" >> $GITHUB_ENV
        echo "NEO4J_USER=neo4j" >> $GITHUB_ENV
        echo "NEO4J_PASSWORD=test123456" >> $GITHUB_ENV
        echo "MONGO_URI=mongodb://localhost:27017" >> $GITHUB_ENV
        echo "MONGO_DB_NAME=testdb" >> $GITHUB_ENV
        echo "MONGO_COLLECTION=entities" >> $GITHUB_ENV
        echo "CRUD_SERVICE_HOST=localhost" >> $GITHUB_ENV
        echo "CRUD_SERVICE_PORT=50051" >> $GITHUB_ENV
        echo "UPDATE_SERVICE_HOST=localhost" >> $GITHUB_ENV
        echo "UPDATE_SERVICE_PORT=8080" >> $GITHUB_ENV

    - name: Build and Start CRUD Service
      run: |
        cd design/crud-api
        go build ./...
        go build -o crud-service cmd/server/service.go cmd/server/utils.go
        ./crud-service &
        echo $! > crud-service.pid

        # Wait for server to be up
        echo "Waiting for crud-service to be ready..."
        for i in {1..30}; do
          if nc -z localhost 50051; then
            echo "crud-service is up!"
            break
          fi
          echo "Still waiting for crud-service..."
          sleep 1
        done

        # Verify service is responding
        echo "Verifying CRUD service is responding..."
        for i in {1..10}; do
          if curl -s http://localhost:50051 > /dev/null; then
            echo "CRUD service is responding!"
            break
          fi
          echo "Still verifying CRUD service..."
          sleep 1
        done

    - name: Test Update API
      shell: bash -l {0}
      run: |
        cd design/update-api
        bal test
        cd ../crud-api
        kill $(cat crud-service.pid)

    - name: Cleanup
      if: always()
      run: |
        if [ -f crud-service.pid ]; then
          kill $(cat crud-service.pid) || true
          rm crud-service.pid
        fi
        /usr/bin/neo4j stop
        /usr/bin/mongod --dbpath /data/db --shutdown
