name: Update API Test

on:
  push:
    branches: [ main ]
    paths:
      - 'nexoan/update-api/**'
      - 'Dockerfile.update'
      - 'docker-compose.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'nexoan/update-api/**'
      - 'Dockerfile.update'
      - 'docker-compose.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and test Update service
      run: |
        # Build Update service
        docker compose build update
        
        # Start required dependencies
        docker compose up -d mongodb neo4j postgres crud
        
        # Wait for dependencies to be healthy
        echo "Waiting for dependencies to be healthy..."
        timeout=300
        while [ $timeout -gt 0 ]; do
          if docker compose ps | grep -q "healthy"; then
            echo "Dependencies are starting to be healthy..."
            break
          fi
          echo "Waiting for health checks... ($timeout seconds remaining)"
          sleep 5
          timeout=$((timeout - 5))
        done
        
        # Wait for CRUD service to complete tests and start the server
        echo "Waiting for CRUD service to complete tests and start server..."
        timeout=600  # 10 minutes for Go tests to complete
        while [ $timeout -gt 0 ]; do
          if docker compose logs crud | grep -q "CRUD Service is running on"; then
            echo "✅ CRUD service is now running!"
            break
          elif docker compose logs crud | grep -q "FAILED\|failed\|error.*test"; then
            echo "❌ CRUD service tests failed!"
            echo "CRUD service logs:"
            docker compose logs crud
            docker compose down
            exit 1
          fi
          echo "Waiting for CRUD service startup... ($timeout seconds remaining)"
          sleep 10
          timeout=$((timeout - 10))
        done
        
        if [ $timeout -le 0 ]; then
          echo "❌ Timeout waiting for CRUD service to start!"
          echo "CRUD service logs:"
          docker compose logs crud
          docker compose down
          exit 1
        fi
        
        # Start Update service in detached mode
        echo "Starting Update service and running tests..."
        docker compose up -d update
        
        # Wait for tests to complete
        echo "Waiting for tests to complete..."
        sleep 30
        
        # Check the logs for test results
        echo "=== Update Service Logs ==="
        docker compose logs update
        
        echo "=== CRUD Service Logs ==="
        docker compose logs crud
        
        echo "=== All Service Status ==="
        docker compose ps
        
        if docker compose logs update | grep -q "failing" && ! docker compose logs update | grep -q "0 failing"; then
          echo "❌ Update API tests failed!"
          echo "Checking for specific error patterns..."
          
          if docker compose logs update | grep -q "500"; then
            echo "🔍 Found HTTP 500 errors - likely CRUD service connectivity issue"
            echo "CRUD service status:"
            docker compose ps crud
          fi
          
          if docker compose logs update | grep -q "Connection refused\|connect: connection refused"; then
            echo "🔍 Found connection refused errors - CRUD service may not be responding"
          fi
          
          docker compose down
          exit 1
        elif docker compose logs update | grep -q "0 failing"; then
          echo "✅ Update API tests passed!"
        else
          echo "⚠️  Test results not found in logs. Checking for service startup..."
          if docker compose logs update | grep -q "Starting Update service\|Running executable"; then
            echo "✅ Update API service started successfully!"
          else
            echo "❌ Could not determine test status and service may not have started properly"
            docker compose down
            exit 1
          fi
        fi
        
        # Cleanup
        docker compose down 