openapi: 3.1.0
info:
  title: Query API
  version: 1.0.0
servers:
  - url: https://api.opendata.com/v1
    description: Production server
paths:
  /entities/root:
    get:
      summary: Get root entity IDs of a given kind
      parameters:
        - name: kind
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of root entity IDs
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: array
                    items:
                      type: string

  /entities/search:
    post:
      summary: Get entities based on id or filter criteria
      description:
        This endpoint allows you to search for entities using either a specific `id` or a set of filter criteria. 

      requestBody:
        required: true
        description: |
          This request body corresponds to the filter criteria used to retrieve entities.

          - It is required to provide **either** `id` or `kind.major`. <br>
          - If `id` is provided, all other filter fields are ignored, and only the matching entity will be returned. <br>
          - If `id` is not provided, `kind.major` becomes required, and additional fields can be included as filters. <br>
          - All other attributes are optional.

        content:
          application/json:
            schema:
              type: object
              required: []
              properties:
                id:
                  type: string
                  description: Required if `kind.major` is not provided
                kind:
                  type: object
                  description: Required if `id` is not provided
                  properties:
                    major:
                      type: string
                      description: Required if `id` is not provided
                    minor:
                      type: string
                name:
                  type: string
                created:
                  type: string
                  format: date-time
                terminated:
                  type: string
                  format: date-time
      responses:
        200:
          description: List of matching entities
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        kind:
                          type: object
                          properties:
                            major:
                              type: string
                            minor:
                              type: string
                        name:
                          type: string
                        created:
                          type: string
                          format: date-time
                        terminated:
                          type: string
                          format: date-time
                          nullable: true

  /entities/{entityId}/metadata:
    get:
      summary: Get metadata of an entity
      parameters:
        - name: entityId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Entity metadata
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                description: >
                  A JSON object containing entity metadata.
                  Structure may vary based on entity type.

  /entities/{entityId}/attributes/{attributeName}:
    get:
      summary: Get entity attribute
      parameters:
        - name: entityId
          in: path
          required: true
          schema:
            type: string
        - name: attributeName
          in: path
          required: true
          schema:
            type: string
        - name: startTime
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: endTime
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: Attribute value(s)
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      start:
                        type: string
                        format: date-time
                      end:
                        type: string
                        format: date-time
                        nullable: true
                      value:
                        type: string
                  - type: array
                    items:
                      type: object
                      properties:
                        start:
                          type: string
                          format: date-time
                        end:
                          type: string
                          format: date-time
                          nullable: true
                        value:
                          type: string
                  - type: "null"

  /entities/{entityId}/relations:
    post:
      summary: Get relationships for an entity based off its id and/or other relationship filters
      description: |
        This endpoint retrieves the relationships of the specified entity, identified by its `entityId`.  
        You can optionally pass filter parameters in the request body to control which relationships are returned.

      parameters:
        - name: entityId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: |
          The request body contains filter parameters used to filter the relationships of the entity identified by `entityId`.  
          This payload is optional - if omitted, the response will include all relationships associated with the given `entityId`.
          All fields in the payload are optional.

          - If the `id` of a relationship is provided in the payload, all other filter fields are ignored, and only the matching relationship will be returned.
          - If the `activeAt` field is provided, the response will include only relationships that were active at that specific timestamp - meaning they were created and not yet terminated at that time.
          - You may use either `activeAt` **or** `startTime`/`endTime` for filtering by time range, but not both.
          - The `direction` can be either **OUTGOING** or **INCOMING** corresponding to the direction of the relationship relative to the entity.

        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Optional relation ID filter
                relatedEntityId:
                  type: string
                  description: Optional related entity ID filter
                name:
                  type: string
                  description: Optional relation name filter
                activeAt:
                  type: string
                  format: date-time
                  description: Filter relations active at this specific time
                startTime:
                  type: string
                  format: date-time
                  description: Filter relations with start time
                endTime:
                  type: string
                  format: date-time
                  description: Filter relations with end time
                direction:
                  type: string
                  description: Filter by relation direction
              description: >
                Filter criteria for relations. Use either activeAt OR startTime/endTime, but not both.
                If no time filters are provided, all relations will be returned.
      responses:
        200:
          description: List of related entities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    relatedEntityId:
                      type: string
                    name:
                      type: string
                    startTime:
                      type: string
                      format: date-time
                    endTime:
                      type: string
                      format: date-time
                    direction:
                      type: string
                    