openapi: 3.1.0
info:
  title: Query API
  version: 1.0.0
servers:
  - url: https://api.opendata.com/v1
    description: Production server
paths:
  /entities/root:
    get:
      summary: Get root entity IDs of a given kind
      parameters:
        - name: kind
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of root entity IDs
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: array
                    items:
                      type: string

  /entities/search:
    post:
      summary: Find entities based on criteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Optional entity ID to search for
                kind:
                  type: object
                  properties:
                    major:
                      type: string
                    minor:
                      type: string
                name:
                  type: string
                created:
                  type: string
                  format: date-time
                terminated:
                  type: string
                  format: date-time
      responses:
        200:
          description: List of matching entities
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        kind:
                          type: object
                          properties:
                            major:
                              type: string
                            minor:
                              type: string
                        name:
                          type: string
                        created:
                          type: string
                          format: date-time
                        terminated:
                          type: string
                          format: date-time
                          nullable: true

  /entities/{entityId}/metadata:
    get:
      summary: Get metadata of an entity
      parameters:
        - name: entityId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Entity metadata
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                description: >
                  A JSON object containing entity metadata.
                  Structure may vary based on entity type.

  /entities/{entityId}/attributes/{attributeName}:
    get:
      summary: Get entity attribute
      parameters:
        - name: entityId
          in: path
          required: true
          schema:
            type: string
        - name: attributeName
          in: path
          required: true
          schema:
            type: string
        - name: startTime
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: endTime
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: Attribute value(s)
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      start:
                        type: string
                        format: date-time
                      end:
                        type: string
                        format: date-time
                        nullable: true
                      value:
                        type: string
                  - type: array
                    items:
                      type: object
                      properties:
                        start:
                          type: string
                          format: date-time
                        end:
                          type: string
                          format: date-time
                          nullable: true
                        value:
                          type: string
                  - type: "null"

  /entities/{entityId}/relations:
    post:
      summary: Get related entity IDs
      parameters:
        - name: entityId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Optional relation ID filter
                relatedEntityId:
                  type: string
                  description: Optional related entity ID filter
                name:
                  type: string
                  description: Optional relation name filter
                activeAt:
                  type: string
                  format: date-time
                  description: Filter relations active at this specific time
                startTime:
                  type: string
                  format: date-time
                  description: Filter relations with start time
                endTime:
                  type: string
                  format: date-time
                  description: Filter relations with end time
                direction:
                  type: string
                  description: Filter by relation direction
              description: >
                Filter criteria for relations. Use either activeAt OR startTime/endTime, but not both.
                If no time filters are provided, all relations will be returned.
      responses:
        200:
          description: List of related entities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    relatedEntityId:
                      type: string
                    name:
                      type: string
                    startTime:
                      type: string
                      format: date-time
                    endTime:
                      type: string
                      format: date-time
                    direction:
                      type: string
                    

  /entities/{entityId}/allrelations:
    post:
      summary: Get all related entity IDs
      description: >
        Retrieves all related entity IDs for the given entity ID without applying any filters.
      parameters:
        - name: entityId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of all related entities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    relatedEntityId:
                      type: string
                    startTime:
                      type: string
                      format: date-time
                    endTime:
                      type: string
                      format: date-time
                    id:
                      type: string
                    name:
                      type: string
